server:
    port: 8081
    sessionTimeout: 30
spring:         
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
    mvc:  
        view:  
            prefix: /WEB-INF/jsp/  
            suffix: .jsp  
    resources:
        static-locations: /WEB-INF/bootstrap-4.0.0-dist,/WEB-INF/customcss,/WEB-INF/imgs
